Feature: Creación de Ejemplares a través de la UI
    Como usuario del sistema
    Quiero crear nuevos ejemplares a través de la interfaz de usuario
    Para poder gestionar el inventario de libros de la biblioteca

Background:
    Given que estoy en la página de creación de ejemplares

Scenario Outline: Crear ejemplar con diferentes combinaciones de datos
    When lleno el formulario de ejemplar con los siguientes datos:
        | Campo              | Valor                |
        | Descripcion        | <Descripcion>        |
        | Observaciones      | <Observaciones>      |
        | FechaAdquisicion   | <FechaAdquisicion>   |
        | Disponible         | <Disponible>         |
    And envío el formulario de ejemplar
    Then debería ver el resultado del ejemplar "<ResultadoEsperado>"

Examples:
    | Caso  | Descripcion                                                                                                                                                                                                        | Observaciones                                                                                                                                               | FechaAdquisicion | Disponible      | ResultadoEsperado |
    | EJM1  | Ejemplar en buen estado                                                                                                                                                                                            |                                                                                                                                                             | 2025-10-19       | No Disponible   | Aceptado          |
    | EJM2  | Ejemplar en buen estado                                                                                                                                                                                            | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                       | 2026-03-23       | Disponible      | Rechazado         |
    | EJM3  | Ejemplar en buen estado                                                                                                                                                                                            | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                       | 2023-01-15       | No Disponible   | Rechazado         |
    | EJM4  | Ejemplar en buen estado                                                                                                                                                                                            | Necesita reparación menor                                                                                                                                  | 2025-10-19       | Disponible      | Aceptado          |
    | EJM5  | ABC                                                                                                                                                                                                                |                                                                                                                                                             | 2026-03-23       | No Disponible   | Rechazado         |
    | EJM6  | ABC                                                                                                                                                                                                                | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                        | 2026-01-15       | Disponible      | Rechazado         |
    | EJM7  | ABC                                                                                                                                                                                                                | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                       | 2025-10-19       | Disponible      | Rechazado         |
    | EJM8  | ABC                                                                                                                                                                                                                | Necesita reparación menor                                                                                                                                  | 2025-10-19       | Disponible      | Aceptado          |
    | EJM9  | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                        | 2025-10-19       | No Disponible   | Rechazado         |
    | EJM10 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                       | 2023-01-15       | Disponible      | Rechazado         |
    | EJM11 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | Necesita reparación menor                                                                                                                                  | 2026-03-23       | Disponible      | Rechazado         |
    | EJM12 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA |                                                                                                                                                             | 2023-01-15       | Disponible      | Rechazado         |
    | EJM13 | AB                                                                                                                                                                                                                 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                       | 2025-10-19       | Disponible      | Rechazado         |
    | EJM14 | AB                                                                                                                                                                                                                 | Necesita reparación menor                                                                                                                                  | 2026-03-23       | Disponible      | Rechazado         |
    | EJM15 | AB                                                                                                                                                                                                                 |                                                                                                                                                             | 2025-10-19       | Disponible      | Rechazado         |
    | EJM16 | AB                                                                                                                                                                                                                 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                        | 2023-01-15       | No Disponible   | Rechazado         |
    | EJM17 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | Necesita reparación menor                                                                                                                                  | 2023-01-15       | Disponible      | Rechazado         |
    | EJM18 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | Necesita reparación menor                                                                                                                                  | 2025-10-19       | No Disponible   | Rechazado         |
    | EJM19 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA |                                                                                                                                                             | 2023-01-15       | Disponible      | Rechazado         |
    | EJM20 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                        | 2025-10-19       | Disponible      | Rechazado         |
    | EJM21 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA                                                       | 2026-03-23       | No Disponible   | Rechazado         |
