// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UITests.Features.Libros
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Creación de Libros a través de la UI")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class CreacionDeLibrosATravesDeLaUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Libros", "Creación de Libros a través de la UI", "    Como usuario del sistema\n    Quiero crear nuevos libros a través de la interf" +
                "az de usuario\n    Para poder gestionar el catálogo de la biblioteca", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LibroCreation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("que estoy en la página de creación de libros", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Libros/LibroCreation.feature.ndjson", 43);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Crear libro con diferentes combinaciones de datos")]
        [global::NUnit.Framework.TestCaseAttribute("LIB1", "Cien años de Soledad", "12345678901234", "", "01/01/2026", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB2", "Cien años de Soledad", "0-306-10615", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "01/15/2020", "A", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB3", "Cien años de Soledad", "0-306-20615", "", "01/15/2020", "English", "AAAAAAAAAAAAAAAAAAA", "Aceptado", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB4", "A", "", "", "01/15/2020", "AAAAAAAAAAAAAAAAAAAAA", "", "Rechazado", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB5", "A", "12345678901234", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "10/19/2025", "Español13@#", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB6", "A", "", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "English", "", "Aceptado", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB7", "A", "12345678901234", "", "01/15/2020", "Es", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB8", "A", "0-306-3", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "10/19/2025", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB9", "A", "0-306-40615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/01/2026", "A", "2da edición", "Rechazado", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB10", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "12345678901234", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "Es", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB11", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "0-306-50615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "AAAAAAAAAAAAAAAAAAA", "2da edición", "Aceptado", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB12", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "", "", "10/19/2025", "A", "", "Rechazado", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB13", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "12345678901234", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/01/2026", "AAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB14", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "0-306-60615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "Español13@#", "2da edición", "Rechazado", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB15", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "01/01/2026", "English", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB16", "¿Quién mató a Palomino Montero?", "0-306-7615", "", "01/01/2026", "Español13@#", "", "Rechazado", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB17", "¿Quién mató a Palomino Montero?", "12345678901234", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "10/19/2025", "English", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB18", "¿Quién mató a Palomino Montero?", "0-306-80615", "", "01/01/2026", "Es", "2da edición", "Rechazado", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB19", "¿Quién mató a Palomino Montero?", "0-306-90615", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "01/15/2020", "AAAAAAAAAAAAAAAAAAA", "", "Rechazado", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB20", "¿Quién mató a Palomino Montero?", "", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "A", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB21", "¿Quién mató a Palomino Montero?", "12345678901234", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "10/19/2025", "AAAAAAAAAAAAAAAAAAAAA", "2da edición", "Rechazado", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB22", "", "", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/01/2026", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB23", "", "12345678901234", "", "01/15/2020", "A", "2da edición", "Rechazado", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB24", "", "0-306-10615", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "01/15/2020", "AAAAAAAAAAAAAAAAAAAAA", "", "Rechazado", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB25", "", "0-306-11615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "10/19/2025", "Español13@#", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB26", "", "", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/01/2026", "English", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB27", "", "0-306-12615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "10/19/2025", "Es", "", "Rechazado", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB28", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "12345678901234", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "10/19/2025", "English", "2da edición", "Rechazado", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB29", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "0-306-13615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/01/2026", "English", "", "Rechazado", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB30", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "0-306-14615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "Es", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB31", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "", "", "10/19/2025", "AAAAAAAAAAAAAAAAAAA", "2da edición", "Rechazado", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB32", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "12345678901234", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/01/2026", "A", "", "Rechazado", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB33", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "0-306-15615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "AAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB34", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "", "", "01/15/2020", "Español13@#", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB35", "Cien años de Soledad", "0-306-16615", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "10/19/2025", "A", "AAAAAAAAAAAAAAAAAAA", "Rechazado", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB36", "Cien años de Soledad", "0-306-17615", "", "01/01/2026", "AAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB37", "Cien años de Soledad", "", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "Español13@#", "2da edición", "Rechazado", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB38", "Cien años de Soledad", "12345678901234", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "English", "", "Rechazado", "37", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB39", "Cien años de Soledad", "0-306-18615", "", "10/19/2025", "English", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB40", "Cien años de Soledad", "", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "01/01/2026", "Es", "2da edición", "Rechazado", "39", null)]
        [global::NUnit.Framework.TestCaseAttribute("LIB41", "Cien años de Soledad", "12345678901234", "Una novela sobre la vida de una familia a lo largo de varias generaciones en el p" +
            "ueblo ficticio de Macondo.", "01/15/2020", "AAAAAAAAAAAAAAAAAAA", "", "Rechazado", "40", null)]
        public async global::System.Threading.Tasks.Task CrearLibroConDiferentesCombinacionesDeDatos(string caso, string titulo, string iSBN, string sinopsis, string fechaPub, string idioma, string edicion, string resultadoEsperado, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("Titulo", titulo);
            argumentsOfScenario.Add("ISBN", iSBN);
            argumentsOfScenario.Add("Sinopsis", sinopsis);
            argumentsOfScenario.Add("FechaPub", fechaPub);
            argumentsOfScenario.Add("Idioma", idioma);
            argumentsOfScenario.Add("Edicion", edicion);
            argumentsOfScenario.Add("ResultadoEsperado", resultadoEsperado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Crear libro con diferentes combinaciones de datos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table7.AddRow(new string[] {
                            "Titulo",
                            string.Format("{0}", titulo)});
                table7.AddRow(new string[] {
                            "ISBN",
                            string.Format("{0}", iSBN)});
                table7.AddRow(new string[] {
                            "Sinopsis",
                            string.Format("{0}", sinopsis)});
                table7.AddRow(new string[] {
                            "FechaPub",
                            string.Format("{0}", fechaPub)});
                table7.AddRow(new string[] {
                            "Idioma",
                            string.Format("{0}", idioma)});
                table7.AddRow(new string[] {
                            "Edicion",
                            string.Format("{0}", edicion)});
#line 10
    await testRunner.WhenAsync("lleno el formulario de libro con los siguientes datos:", ((string)(null)), table7, "When ");
#line hidden
#line 18
    await testRunner.AndAsync("envío el formulario de libro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.ThenAsync(string.Format("debería ver el resultado del libro \"{0}\"", resultadoEsperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
