// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UITests.Features.Libros
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Actualización de Libros a través de la UI")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ActualizacionDeLibrosATravesDeLaUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Libros", "Actualización de Libros a través de la UI", "    Como usuario del sistema\n    Quiero actualizar información de libros existent" +
                "es a través de la interfaz de usuario\n    Para poder mantener actualizado el cat" +
                "álogo de la biblioteca", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LibroUpdate.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
            global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                        "Campo",
                        "Valor"});
            table8.AddRow(new string[] {
                        "Titulo",
                        "Libro de Prueba"});
            table8.AddRow(new string[] {
                        "ISBN",
                        "TEST-INITIAL"});
            table8.AddRow(new string[] {
                        "Sinopsis",
                        "Sinopsis inicial"});
            table8.AddRow(new string[] {
                        "FechaPub",
                        "01/01/2020"});
            table8.AddRow(new string[] {
                        "Idioma",
                        "Español"});
            table8.AddRow(new string[] {
                        "Edicion",
                        "Primera"});
#line 7
    await testRunner.GivenAsync("que existe un libro con los siguientes datos iniciales:", ((string)(null)), table8, "Given ");
#line hidden
#line 15
    await testRunner.AndAsync("estoy en la página de edición de ese libro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Libros/LibroUpdate.feature.ndjson", 18);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Actualizar libro con diferentes combinaciones de datos")]
        [global::NUnit.Framework.TestCaseAttribute("ULB1", "El Quijote", "1234567890123", "Una obra maestra", "01/15/2020", "Español", "Segunda", "Aceptado", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB2", "", "9876543210987", "Sinopsis válida", "06/10/2021", "English", "Primera", "Rechazado", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB3", "Cien Años de Soledad", "12345678901234", "Texto corto", "12/25/2019", "Francés", "Tercera", "Rechazado", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB4", "A", "", "", "", "", "", "Aceptado", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB5", "La Odisea", "111", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "01/01/2026", "A", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB6", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "0-306-40615-2", "Sinopsis de prueba", "03/20/2022", "AAAAAAAAAAAAAAAAAAA", "A", "Rechazado", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB7", "El Principito", "", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "01/01/2026", "Alemán", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB8", "Hamlet", "1111111111111", "Texto de ejemplo", "11/11/2017", "A", "Quinta", "Rechazado", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB9", "Moby Dick", "999-888-777", "Una historia épica", "08/15/2023", "AAAAAAAAAAAAAAAAAAA", "Segunda", "Rechazado", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB10", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "5555555555555", "", "01/01/2026", "Portugués", "A", "Rechazado", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB11", "La Ilíada", "ABC-DEF-GHI", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "02/28/2021", "A", "Primera", "Rechazado", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB12", "Don Juan Tenorio", "", "Sinopsis breve", "05/05/2019", "Catalán", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB13", "Fausto", "2468101214161", "Texto medio", "01/01/2026", "AAAAAAAAAAAAAAAAAAA", "Sexta", "Rechazado", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB14", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "1357924680246", "Una sinopsis", "09/30/2020", "A", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB15", "Guerra y Paz", "9999999999999", "Sinopsis extensa pero válida", "01/01/2026", "Ruso", "A", "Rechazado", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("ULB16", "Los Miserables", "0000000000000", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "12/31/2024", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAA", "Rechazado", "15", null)]
        public async global::System.Threading.Tasks.Task ActualizarLibroConDiferentesCombinacionesDeDatos(string caso, string titulo, string iSBN, string sinopsis, string fechaPub, string idioma, string edicion, string resultadoEsperado, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("Titulo", titulo);
            argumentsOfScenario.Add("ISBN", iSBN);
            argumentsOfScenario.Add("Sinopsis", sinopsis);
            argumentsOfScenario.Add("FechaPub", fechaPub);
            argumentsOfScenario.Add("Idioma", idioma);
            argumentsOfScenario.Add("Edicion", edicion);
            argumentsOfScenario.Add("ResultadoEsperado", resultadoEsperado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Actualizar libro con diferentes combinaciones de datos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table9.AddRow(new string[] {
                            "Titulo",
                            string.Format("{0}", titulo)});
                table9.AddRow(new string[] {
                            "ISBN",
                            string.Format("{0}", iSBN)});
                table9.AddRow(new string[] {
                            "Sinopsis",
                            string.Format("{0}", sinopsis)});
                table9.AddRow(new string[] {
                            "FechaPub",
                            string.Format("{0}", fechaPub)});
                table9.AddRow(new string[] {
                            "Idioma",
                            string.Format("{0}", idioma)});
                table9.AddRow(new string[] {
                            "Edicion",
                            string.Format("{0}", edicion)});
#line 18
    await testRunner.WhenAsync("actualizo el formulario de libro con los siguientes datos:", ((string)(null)), table9, "When ");
#line hidden
#line 26
    await testRunner.AndAsync("envío el formulario de actualización de libro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.ThenAsync(string.Format("debería ver el resultado de actualización de libro \"{0}\"", resultadoEsperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
