// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UITests.Features.Lectores
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Actualización de Lectores a través de la UI")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ActualizacionDeLectoresATravesDeLaUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Lectores", "Actualización de Lectores a través de la UI", "    Como usuario del sistema\n    Quiero actualizar información de lectores existe" +
                "ntes a través de la interfaz de usuario\n    Para poder mantener actualizada la i" +
                "nformación de los usuarios de la biblioteca", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LectorUpdate.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
            global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                        "Campo",
                        "Valor"});
            table3.AddRow(new string[] {
                        "CI",
                        "1234567"});
            table3.AddRow(new string[] {
                        "PrimerNombre",
                        "Test"});
            table3.AddRow(new string[] {
                        "SegundoNombre",
                        "Usuario"});
            table3.AddRow(new string[] {
                        "PrimerApellido",
                        "Prueba"});
            table3.AddRow(new string[] {
                        "SegundoApellido",
                        "Sistema"});
            table3.AddRow(new string[] {
                        "Telefono",
                        "12345678"});
            table3.AddRow(new string[] {
                        "Correo",
                        "test@example.com"});
#line 7
    await testRunner.GivenAsync("que existe un lector con los siguientes datos iniciales:", ((string)(null)), table3, "Given ");
#line hidden
#line 16
    await testRunner.AndAsync("estoy en la página de edición de ese lector", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Lectores/LectorUpdate.feature.ndjson", 17);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Actualizar lector con diferentes combinaciones de datos")]
        [global::NUnit.Framework.TestCaseAttribute("UPD1", "Carlos", "Manuel", "Lopez", "Rodriguez", "9876543210", "87654321", "carlos.lopez@mail.com", "Aceptado", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD2", "Maria", "Jose", "Gonzalez", "Martinez", "123456", "1234567890", "maria@test.com", "Aceptado", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD3", "Pedro", "Luis", "Ramirez", "Fernandez", "7654321", "ABC12345", "pedro.ramirez@example.com", "Rechazado", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD4", "Laura", "AAAAAAAAAAAAAAAAAAAAAAA", "Morales", "Diaz", "", "98765432", "laura@domain.com", "Rechazado", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD5", "Roberto", "J", "J", "Vargas", "11223344556", "11223344", "invalid-email", "Rechazado", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD6", "Sofia", "Cristina", "AAAAAAAAAAAAAAAAAAAAAAAA", "J", "5544332211", "55443322", "sofia.cristina@test.co", "Rechazado", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD7", "AAAAAAAAAAAAAAAAAAAAAAAA", "Ana", "Torres", "AAAAAAAAAAAAAAAAAAAAAAA", "998877", "9988776655", "a@b.c", "Aceptado", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD8", "Miguel", "Angel", "Herrera", "Castro", "445566", "44556677", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Aceptado", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD9", "J", "AAAAAAAAAAAAAAAAAAAAAAA", "Medina", "Rojas", "5566778899", "5566778", "miguel@company.org", "Rechazado", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD10", "Gabriela", "Isabel", "Ortiz", "Delgado", "667788", "66778899", "a@b", "Rechazado", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD11", "Fernando", "Jose", "Navarro", "Ponce", "7788990011", "XYZ123@#", "fernando.navarro@enterprise.com", "Rechazado", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD12", "J", "Maria", "J", "Silva", "8899001122", "88990011", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD13", "Valentina", "Rosa", "Campos", "Reyes", "", "99001122", "valentina@system.net", "Rechazado", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD14", "AAAAAAAAAAAAAAAAAAAAAAAA", "Victoria", "Mendez", "Paredes", "112233", "10111213", "v@test.io", "Aceptado", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("UPD15", "Diego", "AAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAA", "Aguirre", "2233445566", "22334455", "noemailformat", "Rechazado", "14", null)]
        public async global::System.Threading.Tasks.Task ActualizarLectorConDiferentesCombinacionesDeDatos(string casoPrueba, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string cI, string telefono, string correo, string resultadoEsperado, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CasoPrueba", casoPrueba);
            argumentsOfScenario.Add("PrimerNombre", primerNombre);
            argumentsOfScenario.Add("SegundoNombre", segundoNombre);
            argumentsOfScenario.Add("PrimerApellido", primerApellido);
            argumentsOfScenario.Add("SegundoApellido", segundoApellido);
            argumentsOfScenario.Add("CI", cI);
            argumentsOfScenario.Add("Telefono", telefono);
            argumentsOfScenario.Add("Correo", correo);
            argumentsOfScenario.Add("ResultadoEsperado", resultadoEsperado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Actualizar lector con diferentes combinaciones de datos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table4.AddRow(new string[] {
                            "CI",
                            string.Format("{0}", cI)});
                table4.AddRow(new string[] {
                            "PrimerNombre",
                            string.Format("{0}", primerNombre)});
                table4.AddRow(new string[] {
                            "SegundoNombre",
                            string.Format("{0}", segundoNombre)});
                table4.AddRow(new string[] {
                            "PrimerApellido",
                            string.Format("{0}", primerApellido)});
                table4.AddRow(new string[] {
                            "SegundoApellido",
                            string.Format("{0}", segundoApellido)});
                table4.AddRow(new string[] {
                            "Telefono",
                            string.Format("{0}", telefono)});
                table4.AddRow(new string[] {
                            "Correo",
                            string.Format("{0}", correo)});
#line 19
    await testRunner.WhenAsync("actualizo el formulario de lector con los siguientes datos:", ((string)(null)), table4, "When ");
#line hidden
#line 28
    await testRunner.AndAsync("envío el formulario de actualización", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.ThenAsync(string.Format("debería ver el resultado de actualización \"{0}\"", resultadoEsperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
