// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UITests.Features.Lectores
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Creación de Lectores a través de la UI")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class CreacionDeLectoresATravesDeLaUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Lectores", "Creación de Lectores a través de la UI", "    Como usuario del sistema\n    Quiero crear nuevos lectores a través de la inte" +
                "rfaz de usuario\n    Para poder gestionar los usuarios de la biblioteca", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LectorCreation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("que estoy en la página de creación de lectores", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Lectores/LectorCreation.feature.ndjson", 37);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Crear lector con diferentes combinaciones de datos")]
        [global::NUnit.Framework.TestCaseAttribute("LEC1", "Juan", "Sol", "Saa", "Saa", "1464324567", "1234567890", "a@b.c", "Aceptado", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC2", "Juan", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "12345", "1234567", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC3", "Juan", "J", "J", "J", "12345678910", "123456789101", "a@b", "Rechazado", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC4", "Juan", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "", "ABC123@#", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC5", "Juan", "Jose", "Ontiveros", "García", "9416526", "12345678", "Estonoesuncorreo", "Rechazado", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC6", "Ana", "Sol", "AAAAAAAAAAAAAAAAAAAAAAAAA", "J", "", "12345678", "User@example.com", "Rechazado", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC7", "Ana", "AAAAAAAAAAAAAAAAAAAAAAAAA", "J", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "9416526", "12345678", "a@b.c", "Rechazado", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC8", "Ana", "J", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "García", "9416526", "1234567890", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC9", "Ana", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "Ontiveros", "García", "1464324567", "1234567", "a@b", "Rechazado", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC10", "Ana", "Jose", "Ontiveros", "Saa", "12345", "123456789101", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC11", "Ana", "Jose", "Saa", "AAAAAAAAAAAAAAAAAAAAAAAAA", "12345678910", "ABC123@#", "Estonoesuncorreo", "Rechazado", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC12", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "García", "12345", "ABC123@#", "User@example.com", "Rechazado", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC13", "AAAAAAAAAAAAAAAAAAAAAAAAA", "J", "Ontiveros", "Saa", "12345678910", "12345678", "a@b.c", "Rechazado", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC14", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "Ontiveros", "AAAAAAAAAAAAAAAAAAAAAAAAA", "", "12345678", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC15", "AAAAAAAAAAAAAAAAAAAAAAAAA", "Jose", "Saa", "J", "9416526", "1234567890", "a@b", "Rechazado", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC16", "AAAAAAAAAAAAAAAAAAAAAAAAA", "Jose", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "9416526", "1234567", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC17", "AAAAAAAAAAAAAAAAAAAAAAAAA", "Sol", "J", "García", "1464324567", "123456789101", "Estonoesuncorreo", "Rechazado", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC18", "J", "J", "Ontiveros", "J", "9416526", "123456789101", "User@example.com", "Rechazado", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC19", "J", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "Saa", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "1464324567", "ABC123@#", "a@b.c", "Rechazado", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC20", "J", "Jose", "AAAAAAAAAAAAAAAAAAAAAAAAA", "García", "12345", "1234567", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC21", "J", "Jose", "J", "García", "12345678910", "12345678", "a@b", "Rechazado", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC22", "J", "Sol", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "Saa", "", "1234567890", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC23", "J", "AAAAAAAAAAAAAAAAAAAAAAAAA", "Ontiveros", "AAAAAAAAAAAAAAAAAAAAAAAAA", "9416526", "1234567", "Estonoesuncorreo", "Rechazado", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC24", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "García", "", "1234567", "User@example.com", "Rechazado", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC25", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "Jose", "J", "Saa", "9416526", "123456789101", "a@b.c", "Rechazado", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC26", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "Jose", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "9416526", "ABC123@#", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC27", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "Sol", "Ontiveros", "J", "1464324567", "12345678", "a@b", "Rechazado", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC28", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "Ontiveros", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "12345", "12345678", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC29", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "J", "Saa", "García", "12345678910", "1234567890", "Estonoesuncorreo", "Rechazado", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC30", "Juan", "Jose", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "J", "12345", "1234567890", "User@example.com", "Rechazado", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC31", "Juan", "Jose", "Ontiveros", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "12345678910", "1234567", "a@b.c", "Rechazado", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC32", "Juan", "Sol", "Ontiveros", "García", "", "123456789101", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC33", "Juan", "AAAAAAAAAAAAAAAAAAAAAAAAA", "Saa", "García", "9416526", "ABC123@#", "a@b", "Rechazado", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC34", "Juan", "J", "AAAAAAAAAAAAAAAAAAAAAAAAA", "Saa", "9416526", "12345678", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@mail.com", "Rechazado", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("LEC35", "Juan", "AAAAAAAAAAAAAAAAAAAAAAAAAA", "J", "AAAAAAAAAAAAAAAAAAAAAAAAA", "1464324567", "12345678", "Estonoesuncorreo", "Rechazado", "34", null)]
        public async global::System.Threading.Tasks.Task CrearLectorConDiferentesCombinacionesDeDatos(string casoPrueba, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string cI, string telefono, string correo, string resultadoEsperado, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CasoPrueba", casoPrueba);
            argumentsOfScenario.Add("PrimerNombre", primerNombre);
            argumentsOfScenario.Add("SegundoNombre", segundoNombre);
            argumentsOfScenario.Add("PrimerApellido", primerApellido);
            argumentsOfScenario.Add("SegundoApellido", segundoApellido);
            argumentsOfScenario.Add("CI", cI);
            argumentsOfScenario.Add("Telefono", telefono);
            argumentsOfScenario.Add("Correo", correo);
            argumentsOfScenario.Add("ResultadoEsperado", resultadoEsperado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Crear lector con diferentes combinaciones de datos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table2.AddRow(new string[] {
                            "PrimerNombre",
                            string.Format("{0}", primerNombre)});
                table2.AddRow(new string[] {
                            "SegundoNombre",
                            string.Format("{0}", segundoNombre)});
                table2.AddRow(new string[] {
                            "PrimerApellido",
                            string.Format("{0}", primerApellido)});
                table2.AddRow(new string[] {
                            "SegundoApellido",
                            string.Format("{0}", segundoApellido)});
                table2.AddRow(new string[] {
                            "CI",
                            string.Format("{0}", cI)});
                table2.AddRow(new string[] {
                            "Telefono",
                            string.Format("{0}", telefono)});
                table2.AddRow(new string[] {
                            "Correo",
                            string.Format("{0}", correo)});
#line 10
    await testRunner.WhenAsync("lleno el formulario de lector con los siguientes datos:", ((string)(null)), table2, "When ");
#line hidden
#line 19
    await testRunner.AndAsync("envío el formulario", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.ThenAsync(string.Format("debería ver el resultado \"{0}\"", resultadoEsperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
